### PR TITLE
fix #68, #87, #88

### LINKED ISSUE #68: closeOtherTabs
Could you please add the Shortcut to close all the other tabs?
In vimium, there is shortcut as known as closeOtherTabs to do this with just one keyboard command.
Thanks a lot!

### PR DESCRIPTION
**Pull request by luchenyuxx**

### CODE REVIEW

**Comment by luchenyuxx** [comment]
Stop generating hints for disabled input element.

This fixed the issue that one can not select input box in the google page.

**Comment by luchenyuxx** [comment]
Hello, @abrookins,
Please do check my latest commits which improve a lot the hint generating method.

It improves the way sVim works with iframe. Before, sVim just won't work with the contents in an iframe. Now we can follow hints to focus on the iframe contents, work with it, and use ESC to focus back to the main page.

It also improves the way we select elements to generate hints. Before, sVim uses XPath to select elements by tag and attributes. But, it will miss something. For example, in [a raspberry pi page](https://www.raspberrypi.org/products/raspberry-pi-3-model-b-plus/), you can't select the "SPECIFICATIONS" tab. Now we use a DFS to iterate the elements, check the tag, attributes, styles.

I think the hint is the key feature of sVim, and it's very important to perfect it to really replace a mouse.

**Comment by abrookins** [comment]
Today is the day I’m going to finally review all the latest work! Thanks for your continued effort @luchenyuxx!

**Comment by abrookins** [comment]
Nice work on this, @luchenyuxx! Testing locally has gone well. I'm going to merge this PR and release a beta version to get wider testing.

**Pull request merged**
