### PR TITLE
#98 change hint position to fixed

### PR DESCRIPTION
**Pull request by luchenyuxx**

### CODE REVIEW

**Comment by abrookins** [comment]
Hey @luchenyuxx, thanks for looking into #98. My concern about this is that with fixed-position hints, behavior can occur that I consider broken -- e.g. any scrolling done while hints are displayed causes the hints to linger in the wrong places.

I took a crack at this myself to see if we could resolve the problem another way. What do you think of https://github.com/flipxfx/sVim/pull/102 ?

**Comment by luchenyuxx** [comment]
@abrookins 
According to [mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/position), the `static` is the same as `relative` but ignore the `top` `bottom` `left` `right`. If `relative` doesn't work, `static` should not work.

To be honest, I was surprised seeing hints are `absolute` in a hint container when I was inspecting this issue. Because from my understanding, in that case, the hints' position is decided by the container's position. And the container's position can easily change.

I'm not a frontend programmer, correct my if i'm wrong.

**Comment by abrookins** [comment]
I’m also not a frontend developer. 😅 I’ll look into the points you brought
up. However, ‘static’ does work here and fixes the issue. Hmmm. As for
why...

**Comment by luchenyuxx** [comment]
@abrookins if it works then it's a good fix :)

**Comment by abrookins** [comment]
I'm going to close this out because I merged the `static` container PR instead, but thank you for once again looking into an issue. We've been lucky to have your help over the past year!

**Pull request closed without merging**
