### PR TITLE
Implement search function

### PR DESCRIPTION
**Pull request by luchenyuxx**
When pressing t, a command bar appears. It takes the input, then google it in new tab.
When pressing o, do the same, but in current tab.
The same as in cVim.

Why:
I miss a lot these two functions in cVim. Although I can use previous newTab to open a new tab, then use safari's smart search. However, safari always gives the focus to the search bar after I press enter. As consequence, it always costs me one more keystroke "ESC".

Drawbacks:
~~Only support google for now.~~ No search suggestion as in cVim.

### CODE REVIEW

**Comment by abrookins** [comment]
Whoa, this sounds great! I'll test out the PR as soon as I can.

**Comment by luchenyuxx** [comment]
Add support for "google", "duckduckgo", "bing", "yahoo", "baidu", "sogou"

**Comment by luchenyuxx** [comment]
@abrookins Thank you for the review. I fixed them.
For the integration of history and bookmark, I didn't find any way to get user history and bookmark from the safari extension js. I think for the history, we can record the url user visited in sVim. But no idea for bookmark.

**Comment by abrookins** [comment]
I also haven't found an API to get history or bookmarks. However, I'd like to continue looking into the API a bit and thinking about this feature. I have mixed feelings about it.

I agree with you that Safari's behavior around focusing on the search bar is annoying. There's a hack someone proposed to get around this: https://github.com/flipxfx/sVim/pull/19. One option we have is to merge that behavior in, off by default, but with a configuration flag to turn it on.

The command bar in this PR is intriguing, and if it worked like cVim's or Vimperator's, I would merge it. However, the current behavior feels incomplete. I.e., when I type a search query, I expect something to happen: suggestions of _some_ kind. Currently, with these commands, nothing happens.

Recording search history within the plugin feels a bit like a privacy violation. However, if we can't show history and bookmarks, perhaps we ought to show search suggestions from the chosen engine. I'm not sure. 🤔

**Comment by abrookins** [comment]
There are definitely ways to get at Safari's history, bookmarks, and reading list from local programs (e.g., https://github.com/deanishe/go-safari). That doesn't apply to this context, however, and I doubt anyone's going to write (or want to use) some kind of sVim companion app that runs in the background, scraping Safari's bookmarks database.

**Comment by luchenyuxx** [comment]
I can implement the command bar more like cVim's. But it only complete the possible commands.
Search suggestions from search engine is hard, because safari won't let you to send get request outside of the domain.
I think if #19 works well, I can live with that.

**Comment by luchenyuxx** [comment]
The reason that I didn't implement it like the cVim one is that:
All I want is a function that can search for me to walk around the hassle default.
In my experiences with other similar extensions on Chrome or Firefox, even they have much more features integrated into the command bar, what I do most is just type and search. I don't even pay attention to the completions.
I think it's more practical to respect the KISS principal.

**Comment by nikitavoloboev** [comment]
If any of you guys use Alfred. I advise you to check out [this workflow](https://github.com/deanishe/alfred-safari-assistant). It has history, bookmark search as well as ability to search current tabs which is awesome.

Also [Searchio](https://github.com/deanishe/alfred-searchio) workflow allows searching many websites with suggestions. Perhaps that may solve some issues you have @luchenyuxx

**Pull request closed without merging**
